#!/usr/bin/env bash
# Configure Nginx to return a 301 redirect for /redirect_me

apt-get update -y
apt-get install -y nginx

echo "Holberton School for the win!" > /var/www/html/index.html

# Insert the redirect into the default server block
sed -i 's@server_name _;@server_name _;\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}@' /etc/nginx/sites-available/default

# Restart nginx
systemctl restart nginx

